apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
spec:
  selector:
    matchLabels:
      app: will-app
  template:
    metadata:
      labels:
        app: will-app
    spec:
      containers:
      - image: wil42/playground:v2
        name: will-app
        ports:
        - containerPort: 8888
